### ISSUE TITLE
Expand Command

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-editor#1]
I have checked in the first pass at the 'expand' node command.

@qjhart You wanted to use grunt, though grunt is more a task runner and dumps a lot of extra stuff to the terminal.  I think this is a little better suited as just a node command (I could add a shell wrapper?).

Grunt:

```
grunt expand --dir /Users/jrmerz/dev/tmp/calvin-network-data --prmname C116
```

Node

```
node scripts/expand /Users/jrmerz/dev/tmp/calvin-network-data C116
```

**Comment by qjhart** [comment]
This looks great.  Let's keep this as a node command.  Can we can add:
--header
--no-header where if the first line contains no value that can be coerced into a number, then we remove it. from the array?

**Comment by jrmerz** [comment]
Isn't the 'header' about to go away in the updated schema you are about to roll out?

**Comment by qjhart** [comment]
You second set of headers, yes, but it should be okay to have
'date', "inflow"
1921-10-01,45.5
....

On Mon, Jan 26, 2015 at 2:08 PM, Justin Merz notifications@github.com
wrote:

> Isn't the 'header' about to go away in the updated schema you are about to
> roll out?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ucd-cws/calvin-network-editor/issues/1#issuecomment-71548872
> .

## 

Quinn Hart -- Land, Air, and Water Resources -- University of California
Davis, CA 95616-8628

**Comment by qjhart** [comment]
Merged
