### ISSUE TITLE
Defining 'widgets' / custom inputs in JSON schema

### ISSUE THREAD

**Issue by jrmerz** [ucd-cws/calvin-network-editor#2]
I have started a webcomponent JSON editor.  Everything is coming together nicely so far, but any thoughts about adding different input types to the JSON schema?  Something as simple as using the type variable to be something like type="prmname", and the node-search widget is used or type="csv" or type="markdown" for appropriate widgets?

**Comment by qjhart** [comment]
Isn't this handled nicely already with the types.js part of the schema? I can add in an MD-format for the strings, but everything is is there isn't it?

**Comment by qjhart** [comment]
as in type="http://cws.ucdavis.edu/schema/types.json#/prmname"

**Comment by jrmerz** [comment]
So here is a use case.  Prmname at the node level should be a string input.  However prmname's in the array of origins and terminals should be lookup widgets. https://github.com/ucd-cws/calvin-network-data/blob/master/json-schema/prmname_p.json.  Currently the array points at the prmname which says it's of type string.  This is fine, but I'm wondering if we can tell the schema editor which element to use.  Perhaps a 'custom' attribute or a 'element' attribute, something like:

```
{
  type : 'string',
  element : 'cwn-prmname-selector'
}
```

These widgets could then be built with the same interface as a input[type="text"].  Binding to {{value}} and firing on-change events.  Thoughts?

**Comment by qjhart** [comment]
Okay, got it, I think.  So we want to give a hint in the json-schema itself on what to use?  And, I guess presumably, we'd want that to not be too editor specific, but specific enough.  How  about we highjack the 'format' code, which can give hints as to the format of the object.  We can add things like 
format : "prmname-selected-from-existing' as a format type, that's generic enough for the schema, but can be a guide to the tool?

**Comment by jrmerz** [comment]
+1
