### ISSUE TITLE
Replicate Network Data Query

### ISSUE THREAD

**Issue by terencewu** [ucd-cws/calvin-network-editor#4]
Currently, Terence's Network building scripts use the network viewer API as the method for extracting all the data for this tool.  We need to have a similar methodology for getting data from a cloned network-data-tool.  This doens't have to be a service, I guess, could be a grunt command.  I'm not sure what's best.

**Comment by jrmerz** [comment]
Can I get a little more in-depth description on what this task is.

**Comment by jrmerz** [comment]
I think... this has now been implemented.
